### ISSUE TITLE
[web] As admin, the autoplay workaround resets the timestamp after clicking play

### ISSUE THREAD

**Issue by zedeus** [zedeus/kinoplex#10]

**Comment by Rabioli** [comment]
I was testing the server also seeing if I missed a config but I think I didn't, and yeah I was wondering why it stops every time a video finishes and it doesn't continue with the playlist.

I wanted to mount it on my server but it doesn't have much use (or rather is annoying) if I have to hit play for every item in the list.

What's the workaround that you have? Why is a workaround needed?

**Comment by ardek66** [comment]
> Why is a workaround needed?

As of lately, browsers will mute audio from autoplaying video frames, making it a bit finnicky to implement videos playing automatically in a browser without screwing up the audio.

>What's the workaround that you have

In theory it should pause the video until you hit play, then it would automatically fetch the remaining position
Tho it's supposed to only do that for non-admins, the fact that it's done admin-side too is a bug

**Comment by ardek66** [comment]
I think this can be closed as of https://github.com/zedeus/kinoplex/pull/24

**Comment by zedeus** [comment]
Solved by this change: https://github.com/zedeus/kinoplex/pull/24/files#diff-56dd32f3b24f08880868543bfb5be312ee5de4025bee9c2b5f06c5ca9bc86b18R389-R393
